name: Deployment Workflow for Github Pages

on:
  push:
    branches:
      - main

jobs:
  test:
    runs0on: ubuntu-latest
    steps:
     - name: Checkout repository
       uses: actions/checkout@v4
     - name: SAST Scan
       run: grep -r -e "password" -e "secret" -e "keys" .
       # run: grep -Ri -w '(password|passwd|pass|secret|keys)' .


    